site_name: PRIMO
site_url: https://crearobotics.github.io/PRIMO-Docs/
#site_description: PRIMO documentation
#site_author: CREA Robotics
#site_logo: images/logo.png
#site_icon: images/favicon.ico
#repo_url:


nav:
  - Home: index.md
  - Fondamenti: cos_e_la_robotica.md
  - Struttura: struttura_robotica.md
  - Componenti: componenti_primo.md
  - Controllo: controllo_robot.md
  - Programmazione: programmazione.md
  - Programmazione Avanzata: programmazione_avanzata.md
  - Approfondimenti: approfondimenti.md
#theme: readthedocs

theme:
  language: it
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: orange
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - content.code.copy
  icon:
    logo: fontawesome/solid/robot

plugins:
  - search
  - to-pdf:
      download_link: header
  
extra:
  alternate:
    - name: Italiano
      link: /it/
      lang: it

    
